**Task 1: Create and Explore Arrays**
1. Create a 1D array of 10 equally spaced numbers between 0 and 50.
    - Hint: Use np.linspace.
2. Create a 2D array (3x3) of random integers between 1 and 20.
    - Hint: Use np.random.randint.
3. Print the attributes (shape, size, dtype, and ndim) of each array.

In [1]:
import numpy as np

# 1. Create a 1D array of 10 equally spaced numbers between 0 and 50
array_1d = np.linspace(0, 50, 10)

# 2. Create a 2D array (3x3) of random integers between 1 and 20
array_2d = np.random.randint(1, 20, (3, 3))

# 3. Print the attributes (shape, size, dtype and ndim) of each array

# 1D array attributes
print(f"Shape of the 1D array: {array_1d.shape}")
print(f"Size of the 1D array: {array_1d.size}")
print(f"Dtype of the 1D array: {array_1d.dtype}")
print(f"Ndim of the 1D array: {array_1d.ndim}")
print("")

# 2D array attributes
print(f"Shape of the 2D array: {array_2d.shape}")
print(f"Size of the 2D array: {array_2d.size}")
print(f"Dtype of the 2D array: {array_2d.dtype}")
print(f"Ndim of the 2D array: {array_2d.ndim}")

Shape of the 1D array: (10,)
Size of the 1D array: 10
Dtype of the 1D array: float64
Ndim of the 1D array: 1

Shape of the 2D array: (3, 3)
Size of the 2D array: 9
Dtype of the 2D array: int32
Ndim of the 2D array: 2


**Task 2: Perform Array Operations**
1. Create two arrays:
    - a = [1, 2, 3] and b = [4, 5, 6].
2. Perform the following operations:
    - Element-wise addition, subtraction, multiplication, and division.
    - Apply np.sqrt and np.exp to array a.

In [2]:
import numpy as np

# 1. Create the arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 2. Operations
print(f"a + b = {a + b}")
print(f"\na - b = {a - b}")
print(f"\na * b = {a * b}")
print(f"\na / b = {a / b}")
print(f"\nSquare root of a = {np.sqrt(a)}")
print(f"\nExponential (e^x) of a = {np.exp(a)}")

a + b = [5 7 9]

a - b = [-3 -3 -3]

a * b = [ 4 10 18]

a / b = [0.25 0.4  0.5 ]

Square root of a = [1.         1.41421356 1.73205081]

Exponential (e^x) of a = [ 2.71828183  7.3890561  20.08553692]


**Task 3: Indexing and Slicing**
1. Create a 4x4 matrix with values from 1 to 16.
    - Hint: Use np.arange and reshape.
2. Extract:
    - The first row.
    - The last column.
    - A 2x2 subarray from the top-left corner.
3. Modify the second row to [99, 99, 99, 99].

In [3]:
import numpy as np

# 1. Create a 4x4 matrix with values from 1 to 16
matrix = np.arange(1, 17).reshape(4, 4)
print(f"Matrix 4x4 created:\n{matrix}")
# 2. Extract
first_row = matrix[0]
print(f"\nFirst row: {first_row}")

last_column = matrix[:, -1]
print(f"\nlast_column: {last_column}")

subarray_top_left = matrix[:2, :2]
print(f"\n2x2 subarray top-left corner:\n{subarray_top_left}")

# 4. Modify the second row to [99, 99, 99, 99]
matrix[1, :] = 99
print(f"\nMatrix 4x4 modified:\n{matrix}")

Matrix 4x4 created:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

First row: [1 2 3 4]

last_column: [ 4  8 12 16]

2x2 subarray top-left corner:
[[1 2]
 [5 6]]

Matrix 4x4 modified:
[[ 1  2  3  4]
 [99 99 99 99]
 [ 9 10 11 12]
 [13 14 15 16]]


**Task 4: Broadcasting**
1. Create a 1D array x = [1, 2, 3] and a 2D array y = [[4], [5], [6]].
2. Perform addition between x and y using broadcasting.
3. Verify the result's shape and contents.

In [4]:
import numpy as np

# 1. Create the arrays
x = np.array([1, 2, 3])
print(f"X =\n{x}")

y = np.array([[4], [5], [6]])
print(f"\nY =\n{y}")

# 2. X + Y using broadcasting
addition = x + y
print(f"\nX + Y =\n{addition}")

# 3. Showing the shapes
print(f"\nX shape: {x.shape}")
print(f"Y shape: {y.shape}")
print(f"X + Y shape: {addition.shape}")

X =
[1 2 3]

Y =
[[4]
 [5]
 [6]]

X + Y =
[[5 6 7]
 [6 7 8]
 [7 8 9]]

X shape: (3,)
Y shape: (3, 1)
X + Y shape: (3, 3)


**Task 5: Reshaping and Combining**
1. Create a 1D array of numbers from 1 to 12.
2. Reshape it into a 3x4 matrix.
3. Flatten the matrix back into a 1D array.
4. Stack two 2D arrays (of shape 2x3) vertically and horizontally.

In [5]:
import numpy as np

# 1. Create a 1D array of numbers from 1 to 12
array_1d = np.arange(1, 13)
print(f"1D array:\n{array_1d}")

# 2. Reshape to 3x4 matrix
matrix_3x4 = array_1d.reshape(3, 4)
print(f"\n3x4 matrix:\n{matrix_3x4}")

# 3. Back to 1D array
flatten_array = matrix_3x4.flatten()
print(f"\nFlattened array:\n{flatten_array}")

# 4. Stack two 2D arrays (2x3) vertically and horizontally
array1_2x3 = np.random.randint(0, 20, (2, 3))
print(f"\n\nArray 1 (2x3):\n{array1_2x3}")
array2_2x3 = np.random.randint(0, 20, (2, 3))
print(f"\nArray 2 (2x3):\n{array2_2x3}")

vertical_stack = np.vstack((array1_2x3, array2_2x3))
print(f"\nVertical stack:\n{vertical_stack}")
horizontal_stack = np.hstack((array1_2x3, array2_2x3))
print(f"\nHorizontal stack:\n{horizontal_stack}")

1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

3x4 matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


Array 1 (2x3):
[[16 12 11]
 [ 3 14  5]]

Array 2 (2x3):
[[ 5 10  3]
 [ 3 15 13]]

Vertical stack:
[[16 12 11]
 [ 3 14  5]
 [ 5 10  3]
 [ 3 15 13]]

Horizontal stack:
[[16 12 11  5 10  3]
 [ 3 14  5  3 15 13]]
